backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'curated'
    label: 'Curated'
    folder: 'content/curated'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - {
          label: "ID",
          name: "id",
          widget: "ncw-id",
          prefix: "article",        # will generate post-124hfkjas
          timestamp: false,     # will generate 1245119112-post-124hfkjas
      }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { 
          label: "Tags",
          name: "tags",
          widget: "list",
          default: ["mcas"]
        }
      - {
          label: "Publication",
          name: "publication",
          widget: "select",
          multiple: false,
          options: ["The Mast Cell Disease Society", "Pubmed", "mastcell360", "other"],
          default: ["The Mast Cell Disease Society"]
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Link', name: 'link', widget: 'string' }
